export const categories = [
  { label: "ARTIFICIAL INTELLIGENCE", value: "ai_ml" },
  { label: "FRONTEND", value: "frontend" },
  { label: "BACKEND", value: "backend" },
  { label: "FRAMEWORKS", value: "frameworks" },
  { label: "MOBILE", value: "mobile" },
  { label: "HI-TECH", value: "hi_tech" },
  { label: "PLATFORMS / BI TOOLS", value: "platforms_bi" },
  { label: "CMS / ECOMMERCE", value: "cms_ecommerce" },
  { label: "CLOUD / DEVOPS", value: "cloud_devops" },
];

export const technologies = {
  ai_ml: [
    { name: "Python", icon: "/assets/python-icon2.png" },
    { name: "PyTorch", icon: "/assets/pytorch-icon.png" },
    { name: "OpenCV", icon: "/assets/opencv-icon.png" },
    { name: "Numpy", icon: "/assets/numpy-icon.png" },
    { name: "SciPy", icon: "/assets/scipy-icon.png" },
    { name: "TensorFlow", icon: "/assets/tensorflow-icon.png" },
    { name: "TFLite", icon: "/assets/tflite-icon.png" },
    { name: "Keras", icon: "/assets/keras-icon.png" },
    { name: "spaCy", icon: "/assets/spacy-icon.png" },
    { name: "GENSIM", icon: "/assets/gensim-icon.png" },
    { name: "OpenAI", icon: "/assets/chatgpt-icon.png" },
    { name: "LangChain", icon: "/assets/langchain-icon.jpeg" },
    { name: "YOLO", icon: "/assets/yolo-icon.png" },
    { name: "Pandas", icon: "/assets/pandas-icon.png" },
    { name: "Matplotlib", icon: "/assets/metaplitlib-icon.png" },
    { name: "Seaborn", icon: "/assets/seaborn-icon.jpeg" },
    { name: "Meta Llama", icon: "/assets/meta-icon.png" },
    { name: "Anthropic", icon: "/assets/anthrop-icon.png" },
    { name: "Mistral", icon: "/assets/mistral-icon.png" },
    { name: "Knime", icon: "/assets/knime-icon.png" },
    { name: "Orange", icon: "/assets/orange-icon.png" },
  ],
  frontend: [
    { name: "Angular", icon: "/assets/angular-icon.png" },
    { name: "ReactJS", icon: "/assets/react-ion.png" },
    { name: "Next.js", icon: "/assets/nextjs-icon.png" },
    { name: "Vue.js", icon: "/assets/vue.js-icon.png" },
    { name: "JavaScript", icon: "/assets/javascript-icon.png" },
    { name: "TypeScript", icon: "/assets/typescript-icon2.png" },
    { name: "NuxtJS", icon: "/assets/nuxtjs-icon.png" },
    { name: "Tailwind CSS", icon: "/assets/tailwindcss-icon.png" },
    { name: "CSS3", icon: "/assets/css-icon.png" },
    { name: "HTML5", icon: "/assets/html-icon.png" },
    { name: "Knockout JS", icon: "/assets/knockout-icon.png" },
    { name: "jQuery", icon: "/assets/jquery-icon.png" },
    { name: "Bootstrap", icon: "/assets/bootstrap-icon.png" },
    { name: "D3 JS", icon: "/assets/d3js-icon.png" },
    { name: "Backbone.js", icon: "/assets/backbone-icon.png" },
    { name: "Ember.js", icon: "/assets/ember-icon.png" },
  ],
  backend: [
    { name: ".NET", icon: "/assets/dotnet-icon.png" },
    { name: ".NET CORE", icon: "/assets/dotnetcore-icon.png" },
    { name: "Node.js", icon: "/assets/nodejs-icon.png" },
    { name: "Java", icon: "/assets/java-icon.png" },
    { name: "PHP", icon: "/assets/php-icon.png" },
    { name: "Python", icon: "/assets/python-icon2.png" },
  ],
  frameworks: [
    { name: ".NET CORE", icon: "/assets/dotnetcore-icon.png" },
    { name: ".NET MVC", icon: "/assets/dotnetmvc-icon.png" },
    { name: "Nest.js", icon: "/assets/nest.js-icon.png" },
    { name: "Express.js", icon: "/assets/express.js-icon.png" },
    { name: "SpringCloud", icon: "/assets/springcloud-icons.png" },
    { name: "Spring Boot", icon: "/assets/springboot-icon.png" },
    { name: "Hibernate", icon: "/assets/hibernate-icon.png" },
    { name: "Laravel", icon: "/assets/laravel-icon.png" },
    { name: "CodeIgniter", icon: "/assets/codeigniter-icon.png" },
    { name: "Flask", icon: "/assets/flask-icon.png" },
    { name: "Django", icon: "/assets/dango-icon.png" },
  ],
  mobile: [
    { name: "iOS", icon: "/assets/ios-icon.png" },
    { name: "Android", icon: "/assets/android-icon.png" },
    { name: "Swift", icon: "/assets/swift-icon.png" },
    { name: "Kotlin", icon: "/assets/kotlin-icon.png" },
    { name: "React Native", icon: "/assets/reactnative-icon.png" },
    { name: "Flutter", icon: "/assets/flutter-icon.png" },
    { name: "Xamarin", icon: "/assets/xamarin-icon.png" },
    { name: "Unity3D", icon: "/assets/unity3d-icon.png" },
  ],
  // hi_tech: [
  //   { name: "Microservice Architecture", icon: "/assets/microservice-icon.png" },
  //   { name: "MicroFrontend Architecture", icon: "/assets/microfrontend-icon.png" },
  //   { name: "Serverless Architecture", icon: "/assets/severaless-icon.png" },
  //   { name: "EventDriven Architecture", icon: "/assets/eventdriven-icon.png" },
  //   { name: "KAFKA", icon: "/assets/kafka-icon.png" },
  //   { name: "RabbitMQ", icon: "/assets/rabbitmq-icon.png" },
  //   { name: "Metaverse", icon: "/assets/metaverse-icon.png" },
  //   { name: "AR/VR", icon: "/assets/arvr-icon.png" },
  //   { name: "RPA", icon: "/assets/rpa-icon.png" },
  //   { name: "Blockchain", icon: "/assets/blockchain-icon.png" },
  //   { name: "PWA", icon: "/assets/pwa.png" },
  //   { name: "AMP", icon: "/assets/amp-icon.png" },
  //   { name: "SonarQube", icon: "/assets/sonarqube-icon.png" },
  //   { name: "Elastic Search", icon: "/assets/elasticsearch-icon.png" },
  //   { name: "GearMan", icon: "/assets/gearman-icon.png" },
  //   { name: "APIGee", icon: "/assets/apigee-icon.png" },
  //   { name: "soc 2", icon: "/assets/soc2-icon.png" },
  // ],
  // platforms_bi: [
  //   { name: "MS Dynamics 365", icon: "/assets/ms-dynamics-icon.png" },
  //   { name: "Salesforce", icon: "/assets/salseforce-icon.png" },
  //   { name: "Odoo", icon: "/assets/odoo-icon.png" },
  //   { name: "Zoho", icon: "/assets/xoho-icon.png" },
  //   { name: "ServiceNow", icon: "/assets/servicenow-icon.png" },
  //   { name: "Camunda", icon: "/assets/ccamunda-icon.png" },
  //   { name: "PowerBI", icon: "/assets/powerbi-icon.png" },
  //   { name: "Tableau", icon: "/assets/tableau-icon.png" },
  // ],
  cms_ecommerce: [
    { name: "WooCommerce", icon: "/assets/woocommerce.png" },
    { name: "Magento", icon: "/assets/magento-icon.png" },
    { name: "Shopify", icon: "/assets/shopify-icon.png" },
    { name: "WordPress", icon: "/assets/wordpress-icon.png" },
    { name: "Strapi", icon: "/assets/strapi-icon.png" },
    { name: "Umbraco", icon: "/assets/umbraco-icon.png" },
    { name: "Kentico", icon: "/assets/kentico-icon.png" },
    { name: "Sitecore", icon: "/assets/sitecore-icon.png" },
    { name: "Sitefinity", icon: "/assets/siteinfy-icon.png" },
  ],
  cloud_devops: [
    { name: "AWS", icon: "/assets/aws-icon.png" },
    { name: "Azure", icon: "/assets/azure-icon.png" },
    { name: "Google Cloud", icon: "/assets/googlecloud-icon.png" },
    { name: "Oracle", icon: "/assets/oracle-icon.png" },
    { name: "Jenkins", icon: "/assets/jenkins-icon.png" },
    { name: "Maven", icon: "/assets/maven-icon.png" },
    { name: "Terraform", icon: "/assets/terraform-icon.png" },
    { name: "OpenShift", icon: "/assets/openshift-icon.png" },
    { name: "Kubernetes", icon: "/assets/kubernetes-icon.png" },
    { name: "Docker", icon: "/assets/docker-icon.png" },
  ],
};